### ISSUE TITLE
Fix program flow

### ISSUE THREAD

**Issue by probeadd** [ComputingTelU/the-four-hoursemen#1]
# Program flow should be like this:

## Circular Arrangement
1. **Input.** Input parameters are generated by SageMath not by this program. Here is the input parameter that generated by SageMath:

    `M`, `v`, `List Private Matrix` (optional).

    ![image](https://user-images.githubusercontent.com/28044374/29484885-9437bf50-84f2-11e7-9f29-0e5f249e2aa3.png)
    ![image](https://user-images.githubusercontent.com/28044374/29484892-b26b53f6-84f2-11e7-837e-4dd272cc07bd.png)

2. **Process.** 
   Private Key Generation and Public Exchange Value

3. **Output.**
    Show public key exchange value

## Upflow-Downflow
1. **Input.** Input parameters are generated by SageMath not by this program. Here is the input parameter that generated by SageMath:

    `M`, `v`, `List Private Matrix` (optional).

    ![image](https://user-images.githubusercontent.com/28044374/29484885-9437bf50-84f2-11e7-9f29-0e5f249e2aa3.png)
    ![image](https://user-images.githubusercontent.com/28044374/29484892-b26b53f6-84f2-11e7-837e-4dd272cc07bd.png)

2. **Process.** 
   Private Key Generation and Public Exchange Value (Upflow-Downflow)

3. **Output.**
    Show public key exchange value. Upflow process first and then downflow process

**Comment by probeadd** [comment]
@hafizhme @RidhwanD @medindian

**Comment by satriahrh** [comment]
> Input parameters are generated by SageMath not by this program

Well, this should be emphasized @probeadd

**Comment by satriahrh** [comment]
@probeadd can you provide the pseudo code here?
