### ISSUE TITLE
Start to write document

### ISSUE THREAD

**Issue by probeadd** [ComputingTelU/the-four-hoursemen#2]
I think we have to start write our document. Here is the template of IndoSC.

[Template-INDOSC.docx](https://github.com/ComputingTelU/the-four-hoursemen/files/1236176/Template-INDOSC.docx)

**Comment by satriahrh** [comment]
This is not for document versioning, lol. We can use google docs instead, by omitting template given at the first time, then someone put it on template at the end.

**Comment by probeadd** [comment]
Loll ok sorry 😂
